let currentImage = GLB.placeholder;
function toast(msg){const el=document.getElementById('toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2200)}
function showAdmin(){document.getElementById('loginScreen').classList.add('hidden'); document.getElementById('adminShell').classList.remove('hidden'); renderAll();}
function page(name){document.querySelectorAll('.admin-page').forEach(p=>p.classList.remove('active')); document.getElementById('page-'+name).classList.add('active'); document.querySelectorAll('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.page===name)); document.getElementById('adminTitle').textContent={dashboard:'Dashboard',products:'Products',orders:'Orders',appointments:'Appointments',services:'Services',settings:'Settings'}[name];}
function table(rows, empty){return rows.length?rows.join(''):`<div class="empty">${empty}</div>`}
function renderStats(db){document.getElementById('stats').innerHTML=`<div class="stat"><b>${db.products.length}</b><span>Products</span></div><div class="stat"><b>${db.orders.length}</b><span>Orders</span></div><div class="stat"><b>${db.appointments.length}</b><span>Appointments</span></div><div class="stat"><b>${db.services.length}</b><span>Services</span></div>`}
function renderDashboard(db){renderStats(db); document.getElementById('latestOrders').innerHTML=table(db.orders.slice(0,5).map(o=>`<div class="summary-line"><span>${o.id}<br><small>${o.customer}</small></span><b>${GLB.money(o.total)}</b></div>`),'No orders yet.'); document.getElementById('latestAppointments').innerHTML=table(db.appointments.slice(0,5).map(a=>`<div class="summary-line"><span>${a.customer}<br><small>${a.service}</small></span><b>${a.date}</b></div>`),'No appointments yet.')}
function renderProducts(db){document.getElementById('productsTable').innerHTML=`<table class="admin-table"><thead><tr><th>Image</th><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th>Action</th></tr></thead><tbody>${db.products.map(p=>`<tr><td class="logo-cell"><img class="thumb" src="${p.image||GLB.placeholder}"></td><td><b>${p.name}</b><br><span class="small-text">${p.description}</span></td><td>${GLB.money(p.price)}<br>${p.offerPrice?`<span class="pill">Offer ${GLB.money(p.offerPrice)}</span>`:''}</td><td>${p.stock}</td><td><span class="pill">${p.visible?'Visible':'Hidden'}</span>${p.featured?'<br><span class="pill">Home</span>':''}</td><td><div class="actions"><button class="icon-btn dark" data-edit-product="${p.id}">Edit</button><button class="icon-btn" data-del-product="${p.id}">Delete</button></div></td></tr>`).join('')}</tbody></table>`}
function renderOrders(db){document.getElementById('ordersTable').innerHTML=db.orders.length?`<table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>${db.orders.map(o=>`<tr><td><b>${o.id}</b><br><span class="small-text">${o.date}</span></td><td>${o.customer}<br><span class="small-text">${o.phone}<br>${o.email}</span></td><td>${o.items.map(i=>`${i.qty} x ${i.name}`).join('<br>')}</td><td><b>${GLB.money(o.total)}</b></td><td>${o.payment}</td><td><span class="pill">${o.status}</span></td><td><div class="actions"><button class="icon-btn gold" data-order-status="${o.id}" data-status="Paid">Paid</button><button class="icon-btn dark" data-order-status="${o.id}" data-status="Completed">Complete</button><button class="icon-btn" data-del-order="${o.id}">Delete</button></div></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No product orders yet. Place a test order from checkout.</div>'}
function serviceOptions(db){return '<option value="">Select service</option>'+db.services.filter(s=>s.visible).map(s=>`<option>${s.name}</option>`).join('')}
function renderAppointments(db){document.getElementById('appointmentService').innerHTML=serviceOptions(db); document.getElementById('appointmentsTable').innerHTML=`<table class="admin-table"><thead><tr><th>Customer</th><th>Service</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>${db.appointments.map(a=>`<tr><td><b>${a.customer}</b><br><span class="small-text">${a.phone}</span></td><td>${a.service}</td><td>${a.date}<br>${a.time}</td><td><span class="pill">${a.status}</span></td><td><div class="actions"><button class="icon-btn gold" data-appt-status="${a.id}" data-status="Completed">Complete</button><button class="icon-btn" data-appt-status="${a.id}" data-status="Cancelled">Cancel</button><button class="icon-btn" data-del-appt="${a.id}">Delete</button></div></td></tr>`).join('')}</tbody></table>`}
function renderServices(db){document.getElementById('servicesTable').innerHTML=`<table class="admin-table"><thead><tr><th>Service</th><th>Price</th><th>Duration</th><th>Status</th><th>Action</th></tr></thead><tbody>${db.services.map(s=>`<tr><td><b>${s.name}</b></td><td>${GLB.money(s.price)}</td><td>${s.duration}</td><td><span class="pill">${s.visible?'Visible':'Hidden'}</span></td><td><div class="actions"><button class="icon-btn dark" data-edit-service="${s.id}">Edit</button><button class="icon-btn" data-del-service="${s.id}">Delete</button></div></td></tr>`).join('')}</tbody></table>`}
function renderAll(){const db=GLB.load(); renderDashboard(db); renderProducts(db); renderOrders(db); renderAppointments(db); renderServices(db);}
function clearProduct(){const f=document.getElementById('productForm'); f.reset(); f.id.value=''; currentImage=GLB.placeholder; document.getElementById('productPreview').src=currentImage; document.getElementById('productFormTitle').textContent='Add product'}
function clearService(){const f=document.getElementById('serviceForm'); f.reset(); f.id.value=''; document.getElementById('serviceFormTitle').textContent='Add service'}
document.addEventListener('DOMContentLoaded',()=>{
 if(GLB.isAdminLoggedIn()) showAdmin();
 document.getElementById('loginForm').onsubmit=e=>{e.preventDefault(); if(username.value==='admin'&&password.value==='GLB2026'){GLB.setAdminLoggedIn(true); showAdmin()} else toast('Wrong login details')};
 document.getElementById('logoutBtn').onclick=()=>{GLB.setAdminLoggedIn(false); location.reload()};
 document.querySelectorAll('.side-link').forEach(b=>b.onclick=()=>page(b.dataset.page)); document.addEventListener('click',e=>{if(e.target.dataset.go)page(e.target.dataset.go)});
 document.getElementById('resetDb').onclick=()=>{if(confirm('Reset all demo products, orders and appointments?')){GLB.reset(); renderAll(); toast('Demo data reset')}};
 document.getElementById('productImage').onchange=e=>{const file=e.target.files[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{currentImage=reader.result; document.getElementById('productPreview').src=currentImage}; reader.readAsDataURL(file)};
 document.getElementById('usePlaceholder').onclick=()=>{currentImage=GLB.placeholder; document.getElementById('productPreview').src=currentImage};
 document.getElementById('clearProductForm').onclick=clearProduct;
 document.getElementById('productForm').onsubmit=e=>{e.preventDefault(); const f=e.target, db=GLB.load(), id=f.id.value||GLB.uid(); const item={id,name:f.name.value,description:f.description.value,price:Number(f.price.value||0),offerPrice:Number(f.offerPrice.value||0),stock:Number(f.stock.value||0),visible:f.visible.value==='true',featured:f.featured.checked,image:currentImage||GLB.placeholder}; const i=db.products.findIndex(p=>p.id===id); if(i>=0)db.products[i]=item; else db.products.unshift(item); GLB.save(db); clearProduct(); renderAll(); toast('Product saved')};
 document.getElementById('appointmentForm').onsubmit=e=>{e.preventDefault(); const f=new FormData(e.target), db=GLB.load(); db.appointments.unshift({id:GLB.uid(),customer:f.get('customer'),phone:f.get('phone'),service:f.get('service'),date:f.get('date'),time:f.get('time'),status:f.get('status'),notes:f.get('notes')}); GLB.save(db); e.target.reset(); renderAll(); toast('Appointment saved')};
 document.getElementById('clearServiceForm').onclick=clearService;
 document.getElementById('serviceForm').onsubmit=e=>{e.preventDefault(); const f=e.target, db=GLB.load(), id=f.id.value||GLB.uid(); const item={id,name:f.name.value,price:Number(f.price.value||0),duration:f.duration.value,visible:f.visible.value==='true',image:GLB.placeholder}; const i=db.services.findIndex(s=>s.id===id); if(i>=0)db.services[i]=item; else db.services.unshift(item); GLB.save(db); clearService(); renderAll(); toast('Service saved')};
 document.addEventListener('click',e=>{const db=GLB.load(); let changed=false;
  if(e.target.dataset.editProduct){const p=db.products.find(x=>x.id===e.target.dataset.editProduct), f=document.getElementById('productForm'); f.id.value=p.id; f.name.value=p.name; f.description.value=p.description; f.price.value=p.price; f.offerPrice.value=p.offerPrice||''; f.stock.value=p.stock; f.visible.value=String(p.visible); f.featured.checked=!!p.featured; currentImage=p.image||GLB.placeholder; productPreview.src=currentImage; productFormTitle.textContent='Edit product'; page('products'); scrollTo({top:0,behavior:'smooth'});}
  if(e.target.dataset.delProduct&&confirm('Delete this product?')){db.products=db.products.filter(p=>p.id!==e.target.dataset.delProduct); changed=true;}
  if(e.target.dataset.orderStatus){const o=db.orders.find(x=>x.id===e.target.dataset.orderStatus); if(o){o.status=e.target.dataset.status; changed=true;}}
  if(e.target.dataset.delOrder&&confirm('Delete this order?')){db.orders=db.orders.filter(o=>o.id!==e.target.dataset.delOrder); changed=true;}
  if(e.target.dataset.apptStatus){const a=db.appointments.find(x=>x.id===e.target.dataset.apptStatus); if(a){a.status=e.target.dataset.status; changed=true;}}
  if(e.target.dataset.delAppt&&confirm('Delete this appointment?')){db.appointments=db.appointments.filter(a=>a.id!==e.target.dataset.delAppt); changed=true;}
  if(e.target.dataset.editService){const s=db.services.find(x=>x.id===e.target.dataset.editService), f=document.getElementById('serviceForm'); f.id.value=s.id; f.name.value=s.name; f.price.value=s.price; f.duration.value=s.duration; f.visible.value=String(s.visible); serviceFormTitle.textContent='Edit service'; page('services'); scrollTo({top:0,behavior:'smooth'});}
  if(e.target.dataset.delService&&confirm('Delete this service?')){db.services=db.services.filter(s=>s.id!==e.target.dataset.delService); changed=true;}
  if(changed){GLB.save(db); renderAll(); toast('Updated')}
 });
});
