let db = getDb();
const pages = {dashboard:['Dashboard','Manage your salon website.'],products:['Products','Add, edit and hide shop products.'],'add-product':['Add product','Create or edit product details, price, stock and images.'],orders:['Orders','Manage customer product orders.'],appointments:['Appointments','Manage booking requests and appointments.'],services:['Services','Manage services and placeholder images.'],settings:['Settings','Bank transfer, coupon and database tools.']};
const loginScreen=document.getElementById('loginScreen'),adminApp=document.getElementById('adminApp');
function openAdmin(){loginScreen.classList.add('hidden');adminApp.classList.remove('hidden');renderAll();route();}
function closeAdmin(){setAdminLoggedIn(false);location.reload();}
if(isAdminLoggedIn())openAdmin();
document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('username')==='admin'&&f.get('password')==='GLB2026'){setAdminLoggedIn(true);e.target.reset();openAdmin();}else document.getElementById('loginError').textContent='Wrong username or password.';});
document.getElementById('logoutBtn').onclick=closeAdmin;
function route(){const key=(location.hash||'#dashboard').slice(1);document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===key));document.querySelectorAll('.side-link').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+key));document.getElementById('pageTitle').textContent=(pages[key]||pages.dashboard)[0];document.getElementById('pageSub').textContent=(pages[key]||pages.dashboard)[1];}
window.addEventListener('hashchange',route);
function renderAll(){db=getDb();renderStats();renderProducts();renderOrders();renderAppointments();renderServices();renderSettings();}
function renderStats(){statProducts.textContent=db.products.length;statOrders.textContent=db.orders.length;statAppointments.textContent=db.appointments.length;statStock.textContent=db.products.reduce((s,p)=>s+Number(p.stock||0),0);dashOrders.innerHTML=db.orders.slice(0,5).map(o=>`<tr><td>${o.id}</td><td>${o.customer}</td><td>${money(o.total)}</td><td><span class="pill">${o.status}</span></td></tr>`).join('')||'<tr><td>No orders yet.</td></tr>';dashAppointments.innerHTML=db.appointments.slice(0,5).map(a=>`<tr><td>${a.customer}</td><td>${a.service}</td><td>${a.date} ${a.time}</td><td><span class="pill">${a.status}</span></td></tr>`).join('');}
function renderProducts(){productsTable.innerHTML=db.products.map(p=>`<tr><td><img class="thumb" src="${p.image||placeholderProduct}"></td><td><b>${p.name}</b><br><span class="admin-small">${p.description}</span></td><td>${money(p.price)}</td><td>${p.offerPrice?money(p.offerPrice):'-'}</td><td>${p.stock}</td><td><span class="pill">${p.visible?'Visible':'Hidden'}</span></td><td class="actions"><button class="icon-btn" onclick="editProduct('${p.id}')">Edit</button><button class="icon-btn" onclick="toggleProduct('${p.id}')">${p.visible?'Hide':'Show'}</button><button class="icon-btn dark" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join('');}
function editProduct(id){const p=db.products.find(x=>x.id===id);const f=productForm;f.id.value=p.id;f.name.value=p.name;f.description.value=p.description;f.price.value=p.price;f.offerPrice.value=p.offerPrice;f.stock.value=p.stock;f.visible.checked=p.visible;productPreview.src=p.image||placeholderProduct;productFormTitle.textContent='Edit product';location.hash='add-product';}
function toggleProduct(id){const p=db.products.find(x=>x.id===id);p.visible=!p.visible;saveDb(db);renderAll();}
function deleteProduct(id){if(confirm('Delete this product?')){db.products=db.products.filter(p=>p.id!==id);saveDb(db);renderAll();}}
productForm.image.addEventListener('change',async e=>{productPreview.src=await readFileAsDataUrl(e.target.files[0])||placeholderProduct;});
productForm.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(productForm);let image=productPreview.src||placeholderProduct;const file=productForm.image.files[0];if(file) image=await readFileAsDataUrl(file);const item={id:f.get('id')||uid('p'),name:f.get('name'),description:f.get('description'),price:Number(f.get('price')),offerPrice:f.get('offerPrice')?Number(f.get('offerPrice')):'',stock:Number(f.get('stock')),image,visible:productForm.visible.checked};const i=db.products.findIndex(p=>p.id===item.id);i>=0?db.products[i]=item:db.products.unshift(item);saveDb(db);clearProduct();renderAll();location.hash='products';});
function clearProduct(){productForm.reset();productForm.id.value='';productPreview.src=placeholderProduct;productFormTitle.textContent='Add product';productForm.visible.checked=true;} clearProductForm.onclick=clearProduct;productPreview.src=placeholderProduct;
function renderOrders(){ordersTable.innerHTML=db.orders.map(o=>`<tr><td><b>${o.id}</b><br><span class="admin-small">${o.date||''}</span></td><td>${o.customer}<br><span class="admin-small">${o.phone}<br>${o.email||''}</span></td><td>${o.items.map(i=>`${i.qty} x ${i.name}`).join('<br>')}</td><td>${money(o.total)}<br><span class="admin-small">Discount ${money(o.discount||0)}</span></td><td>${o.payment}</td><td><select onchange="updateOrderStatus('${o.id}',this.value)">${['Pending payment','Paid','Processing','Completed','Cancelled'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td><button class="icon-btn dark" onclick="deleteOrder('${o.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No product orders yet.</td></tr>';}
function updateOrderStatus(id,status){const o=db.orders.find(x=>x.id===id);o.status=status;saveDb(db);renderAll();}
function deleteOrder(id){if(confirm('Delete order?')){db.orders=db.orders.filter(o=>o.id!==id);saveDb(db);renderAll();}}
function renderAppointments(){appointmentService.innerHTML=db.services.map(s=>`<option>${s.name}</option>`).join('');appointmentsTable.innerHTML=db.appointments.map(a=>`<tr><td>${a.customer}<br><span class="admin-small">${a.phone}</span></td><td>${a.service}</td><td>${a.date}<br>${a.time}</td><td><select onchange="updateAppointmentStatus('${a.id}',this.value)">${['Requested','Booked','Completed','Cancelled'].map(s=>`<option ${a.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td><button class="icon-btn dark" onclick="deleteAppointment('${a.id}')">Delete</button></td></tr>`).join('');}
appointmentForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(appointmentForm);db.appointments.unshift({id:uid('a'),customer:f.get('customer'),phone:f.get('phone'),service:f.get('service'),date:f.get('date'),time:f.get('time'),status:f.get('status')});saveDb(db);appointmentForm.reset();renderAll();});
function updateAppointmentStatus(id,status){const a=db.appointments.find(x=>x.id===id);a.status=status;saveDb(db);renderAll();}
function deleteAppointment(id){if(confirm('Delete appointment?')){db.appointments=db.appointments.filter(a=>a.id!==id);saveDb(db);renderAll();}}
function renderServices(){servicesTable.innerHTML=db.services.map(s=>`<tr><td><img class="thumb" src="${s.image||placeholderService}"></td><td><b>${s.name}</b><br><span class="admin-small">${s.description}</span></td><td>${money(s.price)}<br><span class="admin-small">${s.duration}</span></td><td class="actions"><button class="icon-btn" onclick="editService('${s.id}')">Edit</button><button class="icon-btn dark" onclick="deleteService('${s.id}')">Delete</button></td></tr>`).join('');}
serviceForm.image.addEventListener('change',async e=>{servicePreview.src=await readFileAsDataUrl(e.target.files[0])||placeholderService;});
function editService(id){const s=db.services.find(x=>x.id===id);serviceForm.id.value=s.id;serviceForm.name.value=s.name;serviceForm.description.value=s.description;serviceForm.price.value=s.price;serviceForm.duration.value=s.duration;serviceForm.visible.checked=s.visible;servicePreview.src=s.image||placeholderService;}
serviceForm.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(serviceForm);let image=servicePreview.src||placeholderService;const file=serviceForm.image.files[0];if(file) image=await readFileAsDataUrl(file);const item={id:f.get('id')||uid('s'),name:f.get('name'),description:f.get('description'),price:Number(f.get('price')),duration:f.get('duration'),image,visible:serviceForm.visible.checked};const i=db.services.findIndex(s=>s.id===item.id);i>=0?db.services[i]=item:db.services.unshift(item);saveDb(db);serviceForm.reset();servicePreview.src=placeholderService;renderAll();});
function deleteService(id){if(confirm('Delete service?')){db.services=db.services.filter(s=>s.id!==id);saveDb(db);renderAll();}}
servicePreview.src=placeholderService;
function renderSettings(){Object.keys(db.settings).forEach(k=>{if(settingsForm[k])settingsForm[k].value=db.settings[k]});}
settingsForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(settingsForm);db.settings={bankName:f.get('bankName'),sortCode:f.get('sortCode'),accountNumber:f.get('accountNumber'),referenceText:f.get('referenceText'),couponCode:f.get('couponCode'),couponPercent:Number(f.get('couponPercent'))};saveDb(db);alert('Settings saved');});
function downloadJson(){const blob=new Blob([JSON.stringify(getDb(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='good-look-browbar-database.json';a.click();}
exportBtn.onclick=downloadJson;downloadDb.onclick=downloadJson;importDb.addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{saveDb(JSON.parse(reader.result));renderAll();alert('Database imported');}catch{alert('Invalid JSON file')}};reader.readAsText(file);});
